services:
  backend:
    build:
      context: .
      target: backend
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      target: frontend
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - backend